### ISSUE TITLE
Transition development + testing to ES and provide ES + CJS for export

### ISSUE THREAD

**Issue by evanplaice** [vanillajs2/absurdum#19]
Currently, this lib is written as ES+ with the dist files and tests being provided as CJS.

Now that Node.JS has experimental support for ESM (EcmaScript Modules), see if it's viable to run/develop/test the code natively in ES6.

## Milestones

- [x] convert tests to ES
- [x] remove chokodir watcher
- [x] verify the import entry-point works

**Comment by evanplaice** [comment]
In GitLab by @evanplaice on Jan 19, 2019, 00:06

changed the description

**Comment by evanplaice** [comment]
In GitLab by @evanplaice on Jan 19, 2019, 00:06

changed the description

**Comment by evanplaice** [comment]
In GitLab by @evanplaice on Jan 19, 2019, 00:07

changed the description

**Comment by evanplaice** [comment]
Completed in 0.8.0
