### ISSUE TITLE
Update Issue/Merge Request template

### ISSUE THREAD

**Issue by evanplaice** [vanillajs2/absurdum#20]
In GitLab by @evanplaice on Jan 19, 2019, 00:12

Make the existing templates work with GitLab and add missing templates

## Milestones

- [x] New Operator Template
- [x] Bug Template
- [x] Enhancement Template
- [x] Merge Request Template
- [x] New Type Template

**Comment by evanplaice** [comment]
In GitLab by @evanplaice on Jan 19, 2019, 00:12

changed the description

**Comment by evanplaice** [comment]
In GitLab by @evanplaice on Jan 19, 2019, 03:18

marked the task **New Operator Template** as completed

**Comment by evanplaice** [comment]
In GitLab by @evanplaice on Jan 19, 2019, 03:18

marked the task **Bug Template** as completed

**Comment by evanplaice** [comment]
In GitLab by @evanplaice on Jan 19, 2019, 03:18

marked the task **Bug Template** as incomplete

**Comment by evanplaice** [comment]
In GitLab by @evanplaice on Jan 19, 2019, 03:18

marked the task **Enhancement Template** as completed

**Comment by evanplaice** [comment]
In GitLab by @evanplaice on Jan 19, 2019, 03:18

marked the task **Bug Template** as completed

**Comment by evanplaice** [comment]
In GitLab by @evanplaice on Jan 19, 2019, 03:18

marked the task **Merge Request Template** as completed

**Comment by evanplaice** [comment]
In GitLab by @evanplaice on Jan 19, 2019, 03:18

marked the task **New Type Template** as completed

**Comment by evanplaice** [comment]
In GitLab by @evanplaice on Jan 19, 2019, 03:18

mentioned in merge request !6

**Comment by evanplaice** [comment]
In GitLab by @evanplaice on Jan 19, 2019, 03:18

created merge request !6 to address this issue

**Comment by evanplaice** [comment]
In GitLab by @evanplaice on Jan 19, 2019, 03:21

closed via merge request !6
